node('haimaxy-jnlp')  {

   stage('Git clone'){
       //echo 'Git pull'
       //checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '${credentialsId}', url: '${url}']]])
       echo 'Git clone'
       git branch: 'master',
           credentialsId: '12345-1234-4696-af25-123455',
           url: 'https://github.com/Raymondma-public/Rayment-backend.git'
       script {
                   build_tag = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
       }
   }

   stage('Gradle Build'){
        echo 'Gradle build'
        //def buildInfo = rtGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish'
        if (isUnix()) {
            dir('RaymentBackend') {
                sh 'chmod a+x gradlew'
                sh './gradlew clean build'
            }
        } else {
            dir('RaymentBackend') {bat 'gradlew.bat clean build'}
        }
    }

    stage('Docker build'){
        echo 'Docker build'
        sh 'docker build -t rayment-backend:${build_tag} .'

    }
    stage('Push docker'){
        echo 'Push docker'
    }

    stage('Deploy K8s'){
            echo 'Deploy to K8s'
            dir('k8s'){
                sh "sed -i 's/<BUILD_TAG>/${build_tag}/' k8s.yaml"
                sh "sed -i 's/<BRANCH_NAME>/${env.BRANCH_NAME}/' k8s.yaml"
                sh "kubectl apply -f raymond-backend-service-deployment.yaml"
            }
    }

}