node {

   stage('Git clone'){
       //echo 'Git pull'
       //checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '${credentialsId}', url: '${url}']]])
       echo 'Git clone'
       git branch: 'master',
           credentialsId: '12345-1234-4696-af25-123455',
           url: 'https://github.com/Raymondma-public/Rayment-backend.git'
   }

   stage('Gradle Build'){
        echo 'Gradle build'
        //def buildInfo = rtGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish'
        if (isUnix()) {
            dir('RaymentBackend') {
                sh 'chmod a+x gradlew'
                sh './gradlew clean build'
            }
        } else {
            dir('RaymentBackend') {bat 'gradlew.bat clean build'}
        }
    }

    stage('Docker build'){
        echo 'Docker build'
        dir('RaymentBackend'){sh 'docker build'}

    }
    stage('Push docker'){
        echo 'Push docker'
    }

    stage('Deploy K8s'){
            echo 'Deploy to K8s'
            dir('RaymentBackend'){sh 'docker build'}
    }

}