kind: Service
apiVersion: v1
metadata:
  name: rayment-backend-service
spec:
  selector:
    app: rayment-backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rayment-backend
spec:
  selector:
    matchLabels:
      app: rayment-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: rayment-backend
    spec:
      containers:
        - name: rayment-backend
          image: raymondmapublic/rayment-backend:v<BUILD_TAG>_<BRANCH_NAME>
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: branch
              value: <BRANCH_NAME>
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Host
                  value: KubernetesLivenessProbe
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Host
                  value: KubernetesLivenessProbe
            initialDelaySeconds: 20