USE `payment` ;

INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AED', 'United Arab Emirates dirham', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AFN', 'Afghani', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ALL', 'Lek', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AMD', 'Armenian Dram', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ANG', 'Netherlands Antillian Guilder', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AOA', 'Kwanza', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ARS', 'Argentine Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AUD', 'Australian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AWG', 'Aruban Guilder', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('AZN', 'Azerbaijanian Manat', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BAM', 'Convertible Marks', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BBD', 'Barbados Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BDT', 'Bangladeshi Taka', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BGN', 'Bulgarian Lev', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BHD', 'Bahraini Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BIF', 'Burundian Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BMD', 'Bermudian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BND', 'Brunei Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BOB', 'Boliviano', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BOV', 'Bolivian Mvdol', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BRL', 'Brazilian Real', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BSD', 'Bahamian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BTN', 'Ngultrum', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BWP', 'Pula', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BYR', 'Belarussian Ruble', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('BZD', 'Belize Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CAD', 'Canadian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CDF', 'Franc Congolais', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CHE', 'WIR Euro', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CHF', 'Swiss Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CHW', 'WIR Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CLF', 'Unidades de formento', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CLP', 'Chilean Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CNY', 'Yuan Renminbi', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('COP', 'Colombian Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('COU', 'Unidad de Valor Real', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CRC', 'Costa Rican Colon', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CUP', 'Cuban Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CVE', 'Cape Verde Escudo', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CYP', 'Cyprus Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('CZK', 'Czech Koruna', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('DJF', 'Djibouti Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('DKK', 'Danish Krone', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('DOP', 'Dominican Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('DZD', 'Algerian Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('EEK', 'Kroon', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('EGP', 'Egyptian Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ERN', 'Nakfa', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ETB', 'Ethiopian Birr', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('EUR', 'Euro', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('FJD', 'Fiji Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('FKP', 'Falkland Islands Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GBP', 'Pound Sterling', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GEL', 'Lari', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GHS', 'Cedi', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GIP', 'Gibraltar pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GMD', 'Dalasi', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GNF', 'Guinea Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GTQ', 'Quetzal', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('GYD', 'Guyana Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('HKD', 'Hong Kong Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('HNL', 'Lempira', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('HRK', 'Croatian Kuna', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('HTG', 'Haiti Gourde', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('HUF', 'Forint', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('IDR', 'Rupiah', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ILS', 'New Israeli Shekel', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('INR', 'Indian Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('IQD', 'Iraqi Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('IRR', 'Iranian Rial', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('ISK', 'Iceland Krona', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('JMD', 'Jamaican Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('JOD', 'Jordanian Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('JPY', 'Japanese yen', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KES', 'Kenyan Shilling', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KGS', 'Som', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KHR', 'Riel', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KMF', 'Comoro Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KPW', 'North Korean Won', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KRW', 'South Korean Won', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KWD', 'Kuwaiti Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KYD', 'Cayman Islands Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('KZT', 'Tenge', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LAK', 'Kip', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LBP', 'Lebanese Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LKR', 'Sri Lanka Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LRD', 'Liberian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LSL', 'Loti', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LTL', 'Lithuanian Litas', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LVL', 'Latvian Lats', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('LYD', 'Libyan Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MAD', 'Moroccan Dirham', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MDL', 'Moldovan Leu', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MGA', 'Malagasy Ariary', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MKD', 'Denar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MMK', 'Kyat', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MNT', 'Tugrik', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MOP', 'Pataca', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MRO', 'Ouguiya', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MTL', 'Maltese Lira', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MUR', 'Mauritius Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MVR', 'Rufiyaa', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MWK', 'Kwacha', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MXN', 'Mexican Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MXV', 'Mexican Unidad de Inversion (UDI)', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MYR', 'Malaysian Ringgit', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('MZN', 'Metical', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NAD', 'Namibian Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NGN', 'Naira', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NIO', 'Cordoba Oro', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NOK', 'Norwegian Krone', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NPR', 'Nepalese Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('NZD', 'New Zealand Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('OMR', 'Rial Omani', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PAB', 'Balboa', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PEN', 'Nuevo Sol', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PGK', 'Kina', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PHP', 'Philippine Peso', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PKR', 'Pakistan Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PLN', 'Zloty', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('PYG', 'Guarani', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('QAR', 'Qatari Rial', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('RON', 'Romanian New Leu', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('RSD', 'Serbian Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('RUB', 'Russian Ruble', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('RWF', 'Rwanda Franc', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SAR', 'Saudi Riyal', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SBD', 'Solomon Islands Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SCR', 'Seychelles Rupee', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SDG', 'Sudanese Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SEK', 'Swedish Krona', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SGD', 'Singapore Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SHP', 'Saint Helena Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SKK', 'Slovak Koruna', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SLL', 'Leone', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SOS', 'Somali Shilling', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SRD', 'Surinam Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('STD', 'Dobra', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SYP', 'Syrian Pound', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('SZL', 'Lilangeni', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('THB', 'Baht', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TJS', 'Somoni', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TMM', 'Manat', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TND', 'Tunisian Dinar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TOP', 'Pa anga', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TRY', 'New Turkish Lira', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TTD', 'Trinidad and Tobago Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TWD', 'New Taiwan Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('TZS', 'Tanzanian Shilling', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('UAH', 'Hryvnia', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('UGX', 'Uganda Shilling', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('USD', 'US Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XAF', 'CFA Franc BEAC', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XAG', 'Silver (one troy ounce)', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XAU', 'Gold (one troy ounce)', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XCD', 'East Carribean Dollar', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XPT', 'Palladium (one troy ounce)', '');
INSERT INTO `payment`.`Supported_Curr` (`curr_code`, `curr_name`, `country`) VALUES ('XXX', 'No Currency', '');
